name = "InflationObservatory"
uuid = "65748f0e-fad4-46de-b690-ab41382e3c69"
version = "0.1.0"
authors = ["Mauricio Vargas <38122573+m4wnn@users.noreply.github.com>"]

[deps]
CPIDataGT = "39a16359-57f0-4aba-960c-77dbb3b4d29c"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
InflationFunctions = "3d0454e0-948f-4743-b998-4d73da99f8a8"
Inflector = "6d011eab-0732-4556-8808-e463c76bf3b6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Mudie = "4d8691f9-d7cd-4649-8446-b9e4aa9b174c"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
CPIDataGT = "0.7.2"
CairoMakie = "0.15.8"
DataFramesMeta = "0.15.6"
Dates = "1.11.0"
DrWatson = "2.19.1"
GLMakie = "0.13.8"
Genie = "5.35.5"
InflationFunctions = "0.5.4"
Inflector = "1.1.0"
Logging = "1.11.0"
Mudie = "0.2.0"
PrettyTables = "3.1.2"
SearchLight = "2.11.2"
WGLMakie = "0.13.8"
