name = "InflationObservatory"
uuid = "2aeb2352-4cf7-4e2d-8d24-b9a857b356f7"
version = "0.1.0"
authors = ["BG-DIE Team"]

[deps]
CPIDataGT = "39a16359-57f0-4aba-960c-77dbb3b4d29c"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
InflationFunctions = "3d0454e0-948f-4743-b998-4d73da99f8a8"
Inoptic = "8f5dd8e8-af9a-4b7e-898c-9283934a1a2b"
Mudie = "4d8691f9-d7cd-4649-8446-b9e4aa9b174c"
StippleMakie = "ca87011c-5f75-4091-8e42-d20fc4be912c"

[compat]
CPIDataGT = "0.7.2"
DrWatson = "2.19.1"
GenieFramework = "3.0.1"
InflationFunctions = "0.5.4"
Inoptic = "0.1.0"
Mudie = "0.2.0"
StippleMakie = "0.1.3"
julia = "1.12.3"
