name = "InflationObservatory"
uuid = "2aeb2352-4cf7-4e2d-8d24-b9a857b356f7"
version = "0.1.0"
authors = ["BG-DIE Team"]

[deps]
CPIDataGT = "39a16359-57f0-4aba-960c-77dbb3b4d29c"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InflationFunctions = "3d0454e0-948f-4743-b998-4d73da99f8a8"
Inoptic = "8f5dd8e8-af9a-4b7e-898c-9283934a1a2b"
Mudie = "4d8691f9-d7cd-4649-8446-b9e4aa9b174c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StippleDownloads = "291a174b-6542-42e7-9996-fc00d7c03310"
StippleMakie = "ca87011c-5f75-4091-8e42-d20fc4be912c"

[compat]
CPIDataGT = "0.7.2"
DataFramesMeta = "0.15.6"
Dates = "1.11.0"
DrWatson = "2.19.1"
GenieFramework = "3.0.1"
HTTP = "1.10.19"
InflationFunctions = "0.5.4"
Inoptic = "0.1.0"
Mudie = "0.3.1"
Random = "1.11.0"
Reexport = "1.2.2"
StippleDownloads = "0.1.5"
StippleMakie = "0.1.3"
julia = "1.12.3"
