name = "InflationObservatory"
uuid = "2aeb2352-4cf7-4e2d-8d24-b9a857b356f7"
version = "0.1.0"
authors = ["BG-DIE Team"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
StippleMakie = "ca87011c-5f75-4091-8e42-d20fc4be912c"

[compat]
DrWatson = "2.19.1"
GenieFramework = "3.0.1"
StippleMakie = "0.1.3"
julia = "1.12.3"
